apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: valaxy-regapp
  type: LoadBalancer   # or NodePort for internal
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
