apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  type: LoadBalancer
  selector:
    app: valaxy-regapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
