apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
spec:
  selector:
    app: valaxy-regapp
  type: LoadBalancer   # or NodePort for internal
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
