apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat-app
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: ramesh9849720900/webapp:latest
        ports:
        - containerPort: 8080
